# 01 - NumPy Basics: Arrays, dtypes, and Creation

A refresher on the foundations of NumPy. Work through the cells, modify them, and predict outputs before running.

## Why NumPy?
- Fast, vectorized numerical computation backed by C
- Homogeneous n-dimensional arrays (`ndarray`)
- Foundation for pandas, scikit-learn, PyTorch, etc.

In [1]:
import numpy as np
print(np.__version__)

2.3.5


## 1. Creating arrays

In [2]:
# From a Python list
a = np.array([1, 2, 3, 4])
print(a, a.dtype, a.shape)

[1 2 3 4] int64 (4,)


In [3]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print('shape:', b.shape, '| ndim:', b.ndim, '| size:', b.size)

[[1 2 3]
 [4 5 6]]
shape: (2, 3) | ndim: 2 | size: 6


In [4]:
# Built-in constructors
print(np.zeros((2, 3)))
print(np.ones((2, 3), dtype=int))
print(np.full((2, 2), 7))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Ranges
print(np.arange(0, 10, 2))      # like range(), supports floats
print(np.linspace(0, 1, 5))     # 5 evenly spaced points incl. endpoints

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## 2. dtypes
NumPy arrays are typed. Pick the right dtype to save memory and avoid surprises.

In [6]:
x = np.array([1, 2, 3], dtype=np.float32)
print(x.dtype, x.nbytes, 'bytes total')

y = x.astype(np.int16)
print(y, y.dtype)

float32 12 bytes total
[1 2 3] int16


## 3. Random arrays
Use the modern `Generator` API (`np.random.default_rng`).

In [7]:
rng = np.random.default_rng(seed=42)
print(rng.random((2, 3)))            # uniform [0,1)
print(rng.normal(0, 1, size=5))      # standard normal
print(rng.integers(0, 10, size=5))   # ints in [0,10)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
[ 0.1278404  -0.31624259 -0.01680116 -0.85304393  0.87939797]
[1 9 7 6 4]


## 4. Reshape & transpose

In [8]:
a = np.arange(12)
print(a.reshape(3, 4))
print(a.reshape(3, 4).T)         # transpose
print(a.reshape(2, 2, 3).shape)  # 3D

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(2, 2, 3)


## Exercises
1. Create a 4x4 array of random floats from a normal distribution with mean 5, std 2.
2. Build a 5x5 identity-like matrix but with 2 on the diagonal.
3. Generate the sequence 0.0, 0.25, 0.5, ..., 5.0 two ways: with `arange` and `linspace`.