# 02 - NumPy Indexing, Slicing & Vectorization

The payoff of NumPy: expressive indexing + fast vectorized math.

In [1]:
import numpy as np
rng = np.random.default_rng(0)

## 1. Basic indexing & slicing

In [2]:
a = np.arange(24).reshape(4, 6)
print(a)
print('row 1:', a[1])
print('elt [2,3]:', a[2, 3])
print('cols 1-3:\n', a[:, 1:4])
print('every other row:\n', a[::2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
row 1: [ 6  7  8  9 10 11]
elt [2,3]: 15
cols 1-3:
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]
every other row:
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]


**Important:** slices are *views*, not copies. Modifying a slice modifies the original.

In [3]:
v = a[0]
v[0] = 999
print(a)  # the original changed!

# Use .copy() to detach
c = a[0].copy()
c[0] = -1
print(a[0])

[[999   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
[999   1   2   3   4   5]


## 2. Boolean (mask) indexing

In [4]:
x = rng.integers(0, 20, size=10)
print(x)
print('mask >10:', x > 10)
print('values:', x[x > 10])

# Modify in place
x[x > 10] = 0
print(x)

[17 12 10  5  6  0  1  0  3 16]
mask >10: [ True  True False False False False False False False  True]
values: [17 12 16]
[ 0  0 10  5  6  0  1  0  3  0]


## 3. Fancy (integer) indexing

In [5]:
a = np.arange(10) * 10
print(a)
idx = [1, 3, 5, 7]
print(a[idx])

[ 0 10 20 30 40 50 60 70 80 90]
[10 30 50 70]


## 4. Vectorized math (no Python loops!)

In [6]:
x = np.arange(1_000_000)

# vectorized — fast
%timeit x * 2 + 1

# python loop — slow (don't do this)
%timeit [v*2 + 1 for v in x[:10000]]  # only 1% of data, still slower

637 μs ± 26.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
639 μs ± 4.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## 5. Broadcasting
Different shapes can combine if compatible (trailing dims align, length-1 dims stretch).

In [7]:
a = np.arange(12).reshape(3, 4)
print('a:\n', a)
print('a + 100:\n', a + 100)            # scalar broadcast
print('a + [0,1,2,3]:\n', a + np.array([0,1,2,3]))   # row broadcast
print('column add:\n', a + np.array([[0],[10],[20]]))  # column broadcast

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a + 100:
 [[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]]
a + [0,1,2,3]:
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
column add:
 [[ 0  1  2  3]
 [14 15 16 17]
 [28 29 30 31]]


## 6. Universal functions (ufuncs)

In [8]:
x = np.linspace(0, np.pi, 5)
print(np.sin(x))
print(np.exp(x))
print(np.sqrt(np.arange(5)))

[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
[ 1.          2.19328005  4.81047738 10.55072407 23.14069263]
[0.         1.         1.41421356 1.73205081 2.        ]


## Exercises
1. Given a 1D array of length 20, set every element divisible by 3 to -1.
2. Make a 5x5 matrix where entry (i, j) = i*10 + j using broadcasting (no loops).
3. Without using `np.mean`, compute the mean of each column of a 4x6 random matrix.