# 03 - NumPy Aggregations, Axes & Linear Algebra

In [1]:
import numpy as np
rng = np.random.default_rng(7)

## 1. Aggregations: sum, mean, std, min/max
The key concept is the **axis**: which dimension to collapse.

In [2]:
a = rng.integers(0, 10, size=(3, 4))
print(a)
print('sum all:', a.sum())
print('sum axis=0 (per column):', a.sum(axis=0))
print('sum axis=1 (per row):  ', a.sum(axis=1))

[[9 6 6 8]
 [5 7 8 2]
 [0 3 2 8]]
sum all: 64
sum axis=0 (per column): [14 16 16 18]
sum axis=1 (per row):   [29 22 13]


In [3]:
print('mean:', a.mean())
print('std :', a.std())
print('min, argmin:', a.min(), a.argmin())
print('max per row:', a.max(axis=1))

mean: 5.333333333333333
std : 2.8087165910587863
min, argmin: 0 8
max per row: [9 8 8]


## 2. Cumulative & sorting

In [4]:
x = rng.integers(0, 10, size=8)
print(x)
print('cumsum :', np.cumsum(x))
print('sorted :', np.sort(x))
print('argsort:', np.argsort(x))   # indices that would sort

[9 0 4 8 1 7 1 4]
cumsum : [ 9  9 13 21 22 29 30 34]
sorted : [0 1 1 4 4 7 8 9]
argsort: [1 4 6 2 7 5 3 0]


## 3. Stacking & splitting

In [5]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)
print(np.vstack([a, b]))
print(np.hstack([a, b]))
print(np.concatenate([a, b], axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## 4. Linear algebra

In [6]:
A = np.array([[1, 2], [3, 4]], dtype=float)
B = np.array([[5, 6], [7, 8]], dtype=float)

print('elementwise A*B:\n', A * B)
print('matmul A@B :\n', A @ B)
print('transpose  :\n', A.T)
print('inverse    :\n', np.linalg.inv(A))
print('determinant:', np.linalg.det(A))

elementwise A*B:
 [[ 5. 12.]
 [21. 32.]]
matmul A@B :
 [[19. 22.]
 [43. 50.]]
transpose  :
 [[1. 3.]
 [2. 4.]]
inverse    :
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinant: -2.0000000000000004


In [7]:
# Solve Ax = b
b = np.array([5, 11], dtype=float)
x = np.linalg.solve(A, b)
print('x =', x)
print('check A@x =', A @ x)

x = [1. 2.]
check A@x = [ 5. 11.]


In [8]:
# Eigen decomposition
eigvals, eigvecs = np.linalg.eig(A)
print('eigenvalues :', eigvals)
print('eigenvectors:\n', eigvecs)

eigenvalues : [-0.37228132  5.37228132]
eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 5. Mini case study: standardize a dataset
Subtract the column mean, divide by the column std (a.k.a. z-score).

In [9]:
data = rng.normal(loc=[10, 100, -5], scale=[2, 20, 1], size=(8, 3))
print('raw:\n', data.round(2))

z = (data - data.mean(axis=0)) / data.std(axis=0)
print('\nz-scored:\n', z.round(2))
print('means ~0:', z.mean(axis=0).round(6))
print('stds  ~1:', z.std(axis=0).round(6))

raw:
 [[ 10.98 107.14  -4.89]
 [  8.14  99.41  -4.3 ]
 [  7.31  90.85  -6.9 ]
 [  7.42  63.17  -5.24]
 [  7.47 105.43  -4.84]
 [  9.63  49.66  -5.54]
 [  9.9  102.27  -6.53]
 [  9.04  80.43  -5.81]]

z-scored:
 [[ 1.76  1.    0.74]
 [-0.47  0.61  1.46]
 [-1.12  0.18 -1.69]
 [-1.03 -1.22  0.33]
 [-1.    0.91  0.81]
 [ 0.7  -1.9  -0.04]
 [ 0.91  0.75 -1.24]
 [ 0.24 -0.35 -0.37]]
means ~0: [-0.  0. -0.]
stds  ~1: [1. 1. 1.]


## Exercises
1. Generate a 100x3 normal matrix and compute the correlation between columns using `np.corrcoef`.
2. Build a function that returns the top-k indices of an array (no Python sort on the whole thing — try `np.argpartition`).
3. Solve the linear system 2x + y = 5, x − 3y = -1 with `np.linalg.solve`.